"""empty message

Revision ID: 3be9e5c12101
Revises: fb4ec18a9284
Create Date: 2018-06-18 18:31:34.136177

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3be9e5c12101'
down_revision = 'fb4ec18a9284'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('menus', 'image_url')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('menus', sa.Column('image_url', sa.VARCHAR(length=128), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
