"""empty message

Revision ID: 865efb49a1a8
Revises: 28671f20f2ac
Create Date: 2018-05-31 21:05:03.312303

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '865efb49a1a8'
down_revision = '28671f20f2ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('menu_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'orders', 'menus', ['menu_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_column('orders', 'menu_id')
    # ### end Alembic commands ###
