"""empty message

Revision ID: 868a051cc263
Revises: 873487e9dadc
Create Date: 2018-06-09 15:57:59.436753

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '868a051cc263'
down_revision = '873487e9dadc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roles', sa.Column('created_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('roles', 'created_at')
    # ### end Alembic commands ###
