"""empty message

Revision ID: 873487e9dadc
Revises: 865efb49a1a8
Create Date: 2018-06-02 00:55:47.993115

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '873487e9dadc'
down_revision = '865efb49a1a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('order_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'order_count')
    # ### end Alembic commands ###
