"""empty message

Revision ID: 8eccf64db17e
Revises: e31c0c44d8b5
Create Date: 2018-09-03 15:22:13.074609

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8eccf64db17e'
down_revision = 'e31c0c44d8b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('menus', sa.Column('date', sa.String(length=20), nullable=True))
    op.drop_column('menus', 'day')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('menus', sa.Column('day', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.drop_column('menus', 'date')
    # ### end Alembic commands ###
