"""empty message

Revision ID: d108e936c61b
Revises: 3be9e5c12101
Create Date: 2018-08-09 00:14:28.375745

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd108e936c61b'
down_revision = '3be9e5c12101'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('menus', sa.Column('image_url', sa.String(length=256), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('menus', 'image_url')
    # ### end Alembic commands ###
